"use client";

export default function PrivacyPolicy() {
     const today = new Date();
  const formattedDate = today.toLocaleDateString('en-US', {
    weekday: 'long', // optional: "Tuesday"
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  return (
    <div className="py-16">
      <div className="container mx-auto px-4 md:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-bold text-deep-blue mb-8">
            Privacy Policy
          </h1>

          <div className="prose prose-lg max-w-none text-gray-700 leading-relaxed">
            <p className="text-gray-600 mb-8">Last Updated: {formattedDate}</p>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-deep-blue mb-4">
                1. General
              </h2>
              <p>
                This document is an electronic record in terms of the
                Information Technology Act, 2000 and the rules made thereunder,
                as applicable, and the amended provisions pertaining to
                electronic records in various statutes as amended by the
                Information Technology Act, 2000. This electronic record is
                generated by a computer system and does not require any physical
                or digital signatures.
              </p>
              <p className="mt-4">
                This Privacy Policy (“Policy”) is published in accordance with
                the provisions of Rule 3(1) of the Information Technology
                (Intermediaries Guidelines) Rules, 2011, requiring publication
                of the privacy policy, terms of use, and other related
                information for access or usage of{" "}
                <strong>https://LegalDhara.in</strong>.
              </p>
              <p className="mt-4">
                The website <strong>LegalDhara.in</strong> (“Website”) is owned
                and operated by <strong>Vibrant Law Associates</strong> (23HWDPS204R1Z4). For the purpose of this Policy:
              </p>
              <ul className="list-disc ml-6 mt-2">
                <li>
                  “<strong>You</strong>” or “<strong>User</strong>” means any
                  legal person or entity accessing or using our services who is
                  competent to enter into binding contracts.
                </li>
                <li>
                  “<strong>We</strong>”, “<strong>Us</strong>”, and “
                  <strong>Our</strong>” refer to Legal Dhara and/or Vibrant Law
                  Associates.
                </li>
              </ul>
              <p className="mt-4">
                By accessing our website and using our services, you agree to
                this Policy and our Terms & Conditions. Continued use of our
                website signifies your acceptance of any modifications to this
                Policy.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-deep-blue mb-4">
                2. Collection of Personal and Other Information
              </h2>
              <p>
                We collect minimal personal information required to provide our
                services, including your name, contact details, and other
                relevant data voluntarily shared through our website. This data
                helps us improve our service quality and user experience.
              </p>
              <p className="mt-4">
                We may also track certain information automatically, such as IP
                addresses, browser types, and interaction patterns for analytics
                and security purposes.
              </p>
              <p className="mt-4 font-medium">
                We do not sell, trade, or rent your personal information to
                others.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-deep-blue mb-4">
                3. Cookies
              </h2>
              <p>
                Legal Dhara may use cookies and similar technologies to enhance
                your browsing experience. Cookies allow us to identify returning
                users, remember preferences, and improve site performance.
              </p>
              <p className="mt-4">
                You may choose to disable cookies in your browser settings, but
                certain features of our website may not function properly as a
                result.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-deep-blue mb-4">
                4. Sharing of Personal Information
              </h2>
              <p>
                We do not share your personal information with third parties
                except when required by law or necessary to deliver our
                services. For instance, we may share limited data with verified
                professionals or payment gateways to fulfill a request or
                transaction initiated by you.
              </p>
              <p className="mt-4">
                Legal Dhara ensures that all partners and service providers
                adhere to data protection standards consistent with this Policy.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-deep-blue mb-4">
                5. Data Security
              </h2>
              <p>
                We use industry-standard security measures to safeguard your
                personal data from unauthorized access, alteration, or
                disclosure. However, due to the inherent nature of the internet,
                absolute security cannot be guaranteed.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-deep-blue mb-4">
                6. Third-Party Links
              </h2>
              <p>
                Our website may contain links to external sites operated by
                third parties. We are not responsible for the privacy practices
                or content of these websites. Users are encouraged to review the
                privacy policies of those external sites.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-deep-blue mb-4">
                7. User Consent
              </h2>
              <p>
                By using our website and services, you consent to the collection
                and use of your information as described in this Policy.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-deep-blue mb-4">
                8. Grievance Officer
              </h2>
              <p>
                In compliance with applicable Indian laws, the Grievance Officer
                for Legal Dhara is:
              </p>
              <ul className="list-none mt-4">
                <li>
                  <strong>Grievance Officer:</strong> [Insert Name]
                </li>
                <li>
                  <strong>Email:</strong>{" "}
                  <a
                    href="mailto:support@LegalDhara.in"
                    className="text-brand-blue underline"
                  >
                    support@LegalDhara.in
                  </a>
                </li>
                <li>
                  <strong>Company:</strong> Vibrant Law Associates
                </li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-deep-blue mb-4">
                9. Dispute Resolution and Jurisdiction
              </h2>
              <p>
                Any dispute arising under this Privacy Policy shall first be
                attempted to be resolved through mutual discussion or mediation.
                If unresolved, it shall be referred to arbitration under the
                Arbitration and Conciliation Act, 1996, with the seat of
                arbitration in <strong>New Delhi, India</strong>.
              </p>
              <p className="mt-4">
                The courts of <strong>New Delhi, India</strong> shall have
                exclusive jurisdiction over disputes arising from this Policy.
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
